# Generated by Django 3.1.4 on 2021-06-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.CharField(max_length=250, verbose_name='Описание')),
                ('level', models.IntegerField(max_length=10)),
                ('Img', models.ImageField(upload_to='img/')),
                ('ImgClean', models.ImageField(upload_to='imgClean/')),
            ],
        ),
    ]
