# Generated by Django 3.1.4 on 2021-07-05 11:56

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('geoApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='Img',
        ),
        migrations.RemoveField(
            model_name='level',
            name='ImgClean',
        ),
        migrations.AddField(
            model_name='level',
            name='img',
            field=sorl.thumbnail.fields.ImageField(default='media/img/map.jpg', upload_to='img/'),
        ),
        migrations.AddField(
            model_name='level',
            name='imgClean',
            field=models.ImageField(default='media/img/map.jpg', upload_to='imgClean/'),
        ),
    ]
