# Generated by Django 3.1.4 on 2021-07-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoApp', '0002_auto_20210705_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='img',
            field=models.ImageField(upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='level',
            name='imgClean',
            field=models.ImageField(upload_to='imgClean/'),
        ),
    ]
